### ISSUE TITLE
Limit this to equivalent resolvers

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-add-requirements#17]
The discussion about resolvers that provide alternative answers is a giant rathole.  We should not build a mechanism for advertising name resolution policies.  That is too complex and filled with questions of policy that are impossible to mechanically evaluate.  Strict equivalence is far simpler to reason about.

This working group isn't really chartered to deal with the myriad of reasons that resolvers might choose not to forward an answer that an authoritative server gives them.

**Comment by chris-box** [comment]
This will certainly require discussion at the interim. In particular we need providers of more than one resolver to say why discovery of their alternatives is useful and can be implemented without descending into said rathole.

**Comment by chris-box** [comment]
The draft is now limited to equivalent resolvers.
