### ISSUE TITLE
Unencrypted forwarders are hardly "classic"

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-add-requirements#19]
The text on DNS forwarders needs to use established nomenclature.  Perhaps "DNS Proxy" as used by RFC 5625.

**Comment by chris-box** [comment]
Agree the correct terminology should be used, but I would look to RFC8499 instead. This mentions RFC5625 and observes that the RFC uses the term "DNS Proxy" without this being defined anywhere. RFC5625 also asserts that most such proxies do not cache, but the very commonly used dnsmasq software caches.

The terms that would appear to be valid from 8499 are "forwarder" and also "stub resolver".

So perhaps this can be resolved by changing "classic unencrypted forwarder" to simply "unencrypted forwarder"?

**Comment by tojens-ietf** [comment]
The use of "classic DNS" to refer to unencrypted use of the DNS protocol over TCP or UDP on port 53 came from a DNSOP discussion regarding the ridiculously long list of unique terms we were using at the time. The latest draft proposing that term alongside terms for other forms of DNS on the wire can be found here:

https://tools.ietf.org/html/draft-ietf-dnsop-terminology-ter-02

**Comment by JoGSal** [comment]
"Do53" seems clear and unambiguous for referring to classic/unencrypted

**Comment by Andrew-419** [comment]
Noting the above comments, perhaps "Do53 forwarder" would suffice?

**Comment by chris-box** [comment]
Draft -01 now uses "Do53" and/or "unencrypted", together with "forwarder" if that is relevant. Closing the issue for now but if the new terminology is still problematic we could reopen.
