### ISSUE TITLE
VPN requirements reduce to nothing

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-add-requirements#23]
I think that there is just one thing that merits the inclusion of the VPN section: the ability to configure a resolver for only a subset of all names.  But I don't think that introduces any requirements.  The essential choice is the same: between parallel configuration for DoT/DoH or talking to the resolver directly.

In other aspects, a VPN is just a network.  The fact that VPN configuration is often strongly authenticated doesn't distinguish it from any other type of network-provided resolver.  I would suggest that we instead acknowledge that VPNs provide another type of network access and configuration methods that might need to be accommodated by parallel discovery methods.

**Comment by chris-box** [comment]
VPNs are now removed from the scope of draft -01.
