### ISSUE TITLE
Usefulness of limited domains

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-add-requirements#24]
Section 4 contains a lot of subsections.  Leaving Section 4.2 (content providers) aside, I can't see any requirement here other than the need to recognize that clients might use a specific resolver for a limited set of names.  I think that this entire section (except 4.2) can be replaced with a sentence and *no* requirements.

**Comment by magicalo** [comment]
I think another subsection is needed similar to 4.2 that describes Recursive DNS Security Providers that behave identically to the way that  Content Providers are described in section 4.2.  The only difference being that a security function is being provided as an outcome.  Alternatively, section 4.2 can describe both CDN and DSP scenarios in a combined paragraph if that is preferred.

**Comment by chris-box** [comment]
Section 4 is now removed from draft -01.
