### ISSUE TITLE
Section 2. Terminology: add definition to terms

### ISSUE THREAD

**Issue by JoGSal** [ietf-wg-add/draft-add-requirements#27]
Taking the definitions in context, one can assume all 3 defined resolvers refer to ones providing Encrypted DNS resolution but then the terms might need to be more explicit, i.e

Associated resolver: A resolver [providing connectivity over Encrypted DNS] operated by the same entity...
Equivalent associated resolver: An associated resolver that provides [Encrypted] DNS responses...
Alternative associated resolver: An associated resolver [using Encrypted transports] that serves different responses...

**Comment by chris-box** [comment]
Draft -01 now uses different definitions, but it's still a good question as to whether equivalent resolvers are always encrypted, or whether they could be unencrypted too. If the new draft's wording is not good enough then I suggest to start a new issue based around that text.
