### ISSUE TITLE
Section 3.2: Add to Requirements

### ISSUE THREAD

**Issue by JoGSal** [ietf-wg-add/draft-add-requirements#29]
- R5.1 If the same entity counts with encrypted services, the Selection mechanisms should default to them.
- R5.2 If no equivalent resolvers are available from the same entity, a disclaimer should be provided to the user where their consent is requested in order to use alternative encrypted resolvers, as user understanding and meaningful choice are vital in this scenario.
- R5.3 A set of rules and standards should be defined for the listing of available resolvers, such as confirming ownership over the encrypted DNS services (google's policy), and maintaining a minimum standard of data handling and management policies (mozilla's policy)

**Comment by chris-box** [comment]
Thanks for the contribution to the "Client-selected resolvers" case. It seems a good start to me. However I'll close the issue as it's no longer in scope of the simplified single use case (draft -01). It would still be useful as part of another document though.
