### ISSUE TITLE
Section 5: Clarification

### ISSUE THREAD

**Issue by JoGSal** [ietf-wg-add/draft-add-requirements#30]
The section says:
"attackers must not be able to: (...) Influence automatic discovery mechanisms such that a client uses one or more resolvers that are not otherwise involved with providing service to the client, such as: (...) a server that the client has manually configured."

What is the precise implication for manually configured servers by the client?

**Comment by chris-box** [comment]
I take this to mean an encrypted DNS server that the user of the client has manually configured, e.g. in browser settings. If my co-authors agree with that interpretation, then you could say it duplicates the second point ("Override or interfere with the resolver preferences of a user or administrator.")
