### ISSUE TITLE
Requirements needed in Discovery of Associated Resolvers (section 3)

### ISSUE THREAD

**Issue by chris-box** [ietf-wg-add/draft-add-requirements#4]
At the moment we only have R1.1 and R1.2.

**Comment by JoGSal** [comment]
R1.3 There must be a mechanism to authenticate the entity that provides the discovered encrypted DNS resolvers
R1.4 There must be a mechanism for a user to signal to the client how to choose between equivalent and alternative resolvers.

**Comment by chris-box** [comment]
Thanks for the good contribution, but as it relates to the former scope which contained alternative resolvers, I'll close this. When a wider scope is resumed in the future something similar may be needed.
